/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ShareChatIdRouteImport } from './routes/share.$chatId'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsHistoryRouteImport } from './routes/settings/history'
import { Route as SettingsCustomizationRouteImport } from './routes/settings/customization'
import { Route as SettingsContactRouteImport } from './routes/settings/contact'
import { Route as SettingsConnectorsRouteImport } from './routes/settings/connectors'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as CChatIdRouteImport } from './routes/c.$chatId'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiRateLimitsRouteImport } from './routes/api.rate-limits'
import { Route as ApiCreateChatRouteImport } from './routes/api.create-chat'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiComposioStatusRouteImport } from './routes/api.composio.status'
import { Route as ApiComposioDisconnectRouteImport } from './routes/api.composio.disconnect'
import { Route as ApiComposioConnectRouteImport } from './routes/api.composio.connect'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareChatIdRoute = ShareChatIdRouteImport.update({
  id: '/share/$chatId',
  path: '/share/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomizationRoute = SettingsCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsContactRoute = SettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectorsRoute = SettingsConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRateLimitsRoute = ApiRateLimitsRouteImport.update({
  id: '/api/rate-limits',
  path: '/api/rate-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateChatRoute = ApiCreateChatRouteImport.update({
  id: '/api/create-chat',
  path: '/api/create-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposioStatusRoute = ApiComposioStatusRouteImport.update({
  id: '/api/composio/status',
  path: '/api/composio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposioDisconnectRoute = ApiComposioDisconnectRouteImport.update({
  id: '/api/composio/disconnect',
  path: '/api/composio/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposioConnectRoute = ApiComposioConnectRouteImport.update({
  id: '/api/composio/connect',
  path: '/api/composio/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-chat': typeof ApiCreateChatRoute
  '/api/rate-limits': typeof ApiRateLimitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$chatId': typeof CChatIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/auth': typeof AuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/composio/connect': typeof ApiComposioConnectRoute
  '/api/composio/disconnect': typeof ApiComposioDisconnectRoute
  '/api/composio/status': typeof ApiComposioStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-chat': typeof ApiCreateChatRoute
  '/api/rate-limits': typeof ApiRateLimitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$chatId': typeof CChatIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/auth': typeof AuthIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/composio/connect': typeof ApiComposioConnectRoute
  '/api/composio/disconnect': typeof ApiComposioDisconnectRoute
  '/api/composio/status': typeof ApiComposioStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-chat': typeof ApiCreateChatRoute
  '/api/rate-limits': typeof ApiRateLimitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/c/$chatId': typeof CChatIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/contact': typeof SettingsContactRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/share/$chatId': typeof ShareChatIdRoute
  '/auth/': typeof AuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/composio/connect': typeof ApiComposioConnectRoute
  '/api/composio/disconnect': typeof ApiComposioDisconnectRoute
  '/api/composio/status': typeof ApiComposioStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/create-chat'
    | '/api/rate-limits'
    | '/auth/callback'
    | '/auth/error'
    | '/c/$chatId'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/connectors'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/share/$chatId'
    | '/auth'
    | '/settings/'
    | '/api/composio/connect'
    | '/api/composio/disconnect'
    | '/api/composio/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/security'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/create-chat'
    | '/api/rate-limits'
    | '/auth/callback'
    | '/auth/error'
    | '/c/$chatId'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/connectors'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/share/$chatId'
    | '/auth'
    | '/settings'
    | '/api/composio/connect'
    | '/api/composio/disconnect'
    | '/api/composio/status'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/create-chat'
    | '/api/rate-limits'
    | '/auth/callback'
    | '/auth/error'
    | '/c/$chatId'
    | '/settings/api-keys'
    | '/settings/attachments'
    | '/settings/connectors'
    | '/settings/contact'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/share/$chatId'
    | '/auth/'
    | '/settings/'
    | '/api/composio/connect'
    | '/api/composio/disconnect'
    | '/api/composio/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCreateChatRoute: typeof ApiCreateChatRoute
  ApiRateLimitsRoute: typeof ApiRateLimitsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  CChatIdRoute: typeof CChatIdRoute
  ShareChatIdRoute: typeof ShareChatIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiComposioConnectRoute: typeof ApiComposioConnectRoute
  ApiComposioDisconnectRoute: typeof ApiComposioDisconnectRoute
  ApiComposioStatusRoute: typeof ApiComposioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$chatId': {
      id: '/share/$chatId'
      path: '/share/$chatId'
      fullPath: '/share/$chatId'
      preLoaderRoute: typeof ShareChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/contact': {
      id: '/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof SettingsContactRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connectors': {
      id: '/settings/connectors'
      path: '/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof SettingsConnectorsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rate-limits': {
      id: '/api/rate-limits'
      path: '/api/rate-limits'
      fullPath: '/api/rate-limits'
      preLoaderRoute: typeof ApiRateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-chat': {
      id: '/api/create-chat'
      path: '/api/create-chat'
      fullPath: '/api/create-chat'
      preLoaderRoute: typeof ApiCreateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/composio/status': {
      id: '/api/composio/status'
      path: '/api/composio/status'
      fullPath: '/api/composio/status'
      preLoaderRoute: typeof ApiComposioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/composio/disconnect': {
      id: '/api/composio/disconnect'
      path: '/api/composio/disconnect'
      fullPath: '/api/composio/disconnect'
      preLoaderRoute: typeof ApiComposioDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/composio/connect': {
      id: '/api/composio/connect'
      path: '/api/composio/connect'
      fullPath: '/api/composio/connect'
      preLoaderRoute: typeof ApiComposioConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsConnectorsRoute: typeof SettingsConnectorsRoute
  SettingsContactRoute: typeof SettingsContactRoute
  SettingsCustomizationRoute: typeof SettingsCustomizationRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsConnectorsRoute: SettingsConnectorsRoute,
  SettingsContactRoute: SettingsContactRoute,
  SettingsCustomizationRoute: SettingsCustomizationRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCreateChatRoute: ApiCreateChatRoute,
  ApiRateLimitsRoute: ApiRateLimitsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  CChatIdRoute: CChatIdRoute,
  ShareChatIdRoute: ShareChatIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiComposioConnectRoute: ApiComposioConnectRoute,
  ApiComposioDisconnectRoute: ApiComposioDisconnectRoute,
  ApiComposioStatusRoute: ApiComposioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
