import { useAuthActions } from "@convex-dev/auth/react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PopoverContent } from "@/components/ui/popover";
import { APP_NAME } from "@/lib/config";

export function PopoverContentAuth() {
	const [isLoading, setIsLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const { signIn } = useAuthActions();

	const handleSignInWithGoogle = async () => {
		try {
			setIsLoading(true);
			setError(null);

			await signIn("google");
		} catch (_err: unknown) {
			// console.error('Error signing in with Google:', err);
			setError("Unable to sign in at the moment. Please try again later.");
			// TODO: send `err` to Sentry / console for diagnostics
		} finally {
			setIsLoading(false);
		}
	};
	return (
		<PopoverContent
			align="start"
			className="w-[300px] overflow-hidden rounded-xl p-0"
			side="top"
		>
			<img
				alt={`calm paint generated by ${APP_NAME}`}
				className="h-32 w-full object-cover"
				src="/banner_forest.jpg"
			/>
			{error ? (
				<div className="rounded-md bg-destructive/10 p-3 text-destructive text-sm">
					{error}
				</div>
			) : null}
			<div className="p-3">
				<p className="mb-1 font-medium text-base text-primary">
					Login to try more features for free
				</p>
				<p className="mb-5 text-base text-muted-foreground">
					Add files, use more models. <br />
					Soon search, agents, and more.
				</p>
				<Button
					className="w-full text-base"
					disabled={isLoading}
					onClick={handleSignInWithGoogle}
					size="lg"
					variant="secondary"
				>
					<img
						alt="Google logo"
						className="mr-2 size-4"
						src="https://www.google.com/favicon.ico"
					/>
					<span>{isLoading ? "Connecting..." : "Continue with Google"}</span>
				</Button>
			</div>
		</PopoverContent>
	);
}
